---
trigger:
  branches:
    include: [ master ]

pr: [ master ]

jobs:
  - job: test
    pool:
      vmImage: 'Ubuntu 16.04'
    container: tpayet/chiquitita:latest
    steps:
      - script: |
           echo "whouhou"
        displayName: 'Say wouhou'

  - job: build
    dependsOn:
      - test
    condition: succeeded()
    pool:
      vmImage: 'Ubuntu 16.04'
    container: tpayet/chiquitita:latest
    steps:
      - script: |
          echo "Release time baby"
        displayName: 'Say release'
      - task: CopyFiles@2
        inputs:
          contents: '$(System.DefaultWorkingDirectory)/release.lol'
          targetFolder: $(Build.ArtifactStagingDirectory)
        displayName: 'Copy build'
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: release.lol
        displayName: 'Upload artifacts'

