---
trigger:
  branches:
    include: 
      - master
      - refs/tags/{tagname}

pr: [ master ]

jobs:
  - job: test
    pool:
      vmImage: 'Ubuntu 16.04'
    container: tpayet/chiquitita:latest
    steps:
      - script: |
           echo "whouhou"
        displayName: 'Say wouhou'

  - job: build
    dependsOn:
      - test
    condition: succeeded()
    pool:
      vmImage: 'Ubuntu 16.04'
    container: tpayet/chiquitita:latest
    steps:
      - script: |
          echo "Release time baby "$(tagName)
        displayName: 'Say release'
      - task: CopyFiles@2
        inputs:
          contents: '$(System.DefaultWorkingDirectory)/release.lol'
          targetFolder: $(Build.ArtifactStagingDirectory)
        displayName: 'Copy build'
      - task: PublishBuildArtifacts@1
        inputs:
          artifactName: release.lol
        displayName: 'Upload artifacts'
      - task: GitHubRelease@0
        condition:
        inputs:
          gitHubConnection: tpayet
          repositoryName: meilisearch/MeiliDB
          target: '$(Build.SourceVersion)'
          action: 'edit'
          tag: $(tagName)
          assets: $(Build.ArtifactStagingDirectory)/*.lol
        displayName: 'Release binaries on guthib'


